import GithubSlugger from "github-slugger";

export interface OutlineHeading {
  id: string;
  level: number;
  text: string;
}

export interface DocumentStats {
  lines: number;
  words: number;
  chars: number;
  readingMinutes: number;
}

const AVG_WORDS_PER_MINUTE = 200;

// Strip inline markdown markers so the outline shows clean labels.
function stripInlineMarkdown(text: string): string {
  return text
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/__([^_]+)__/g, "$1")
    .replace(/_([^_]+)_/g, "$1")
    .replace(/~~([^~]+)~~/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .trim();
}

/**
 * Extract headings from markdown, skipping fenced code blocks.
 * Heading ids match those generated by `rehype-slug` (github-slugger).
 */
export function extractOutline(markdown: string): OutlineHeading[] {
  const slugger = new GithubSlugger();
  const headings: OutlineHeading[] = [];
  let insideFence = false;
  let fenceMarker = "";

  for (const rawLine of markdown.split("\n")) {
    const line = rawLine.trimEnd();
    const fenceMatch = /^(```|~~~)/.exec(line.trim());
    if (fenceMatch) {
      const marker = fenceMatch[1];
      if (!insideFence) {
        insideFence = true;
        fenceMarker = marker;
      } else if (marker === fenceMarker) {
        insideFence = false;
        fenceMarker = "";
      }
      continue;
    }
    if (insideFence) continue;

    const headingMatch = /^(#{1,6})\s+(.*)$/.exec(line);
    if (headingMatch) {
      const level = headingMatch[1].length;
      const text = stripInlineMarkdown(headingMatch[2].replace(/#+\s*$/, ""));
      if (!text) continue;
      headings.push({ id: slugger.slug(text), level, text });
    }
  }

  return headings;
}

export function countStats(markdown: string): DocumentStats {
  const trimmed = markdown.trim();
  const lines = markdown.split("\n").length;
  const words = trimmed === "" ? 0 : trimmed.split(/\s+/).length;
  const chars = markdown.length;
  const readingMinutes = Math.max(1, Math.round(words / AVG_WORDS_PER_MINUTE));
  return { lines, words, chars, readingMinutes };
}
